---
abstract: 'Dynamic generation of tests in nested combinations of contexts'
author:
  - 'Tim Bunce'
build_requires:
  Test::Directory: '0.041'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-WriteVariants
no_index:
  directory:
    - t
    - inc
recommends:
  File::HomeDir: '0.50'
  List::MoreUtils: '0.22'
requires:
  Data::Tumbler: '0.002'
  Module::Pluggable::Object: '4.9'
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-WriteVariants
  homepage: https://metacpan.org/release/Test-WriteVariants
  license: http://dev.perl.org/licenses/
  repository: https://github.com/perl5-utils/Test-WriteVariants
version: '0.009'
